version: "3.1"

services:
  postgres:
    image: postgres:11
    restart: always
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: "getmein"

  hasura:
    image: hasura/graphql-engine:v1.3.3
    ports:
      - 8080:8080
    depends_on:
      - postgres
    restart: always
    environment:
      HASURA_GRAPHQL_DATABASE_URL: "postgres://postgres:getmein@postgres:5432/postgres"
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true"
      HASURA_GRAPHQL_ADMIN_SECRET: "iamadmin"
